version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise:8.2.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    user: '104'
    depends_on:
      - prometheus